### ISSUE TITLE
Enable post revisions

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/themeisle-blog#1]
https://support.pagely.com/hc/en-us/articles/210623337-Post-Revisions

**Comment by ineagu** [comment]
@selu91 eu nu am cheia aici, poti modifica tu ?

**Comment by selu91** [comment]
ai modificat ? @ineagu

**Comment by ineagu** [comment]
ma omoara iar cheile si permisiunile pe mac :((. modifica si tu linia aia

On Thu, May 19, 2016 at 2:23 PM, Marius Cristea <notifications@github.com>
wrote:

> Assigned #1 <https://github.com/Codeinwp/themeisle-blog/issues/1> to
> @ineagu <https://github.com/ineagu>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Codeinwp/themeisle-blog/issues/1#event-665718503>
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com

**Comment by selu91** [comment]
@ineagu l-am pus

**Comment by ineagu** [comment]
one more thing, re the TI blog, are we limiting the number of revisions somehow in the wp-config?

I think I'm not seeing all of them when I edit a post
