### ISSUE TITLE
UI changes feedback [mobile issues]

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/themeisle-blog#11]
@abaicus I kept looking at the re-design impact for the blog and I noticed few things, while some stuff looked good, most of them didn't, today while I was checking the site on mobile, I easily realise it looks worst than before, so I decided to digg more into it:

Here is how outbound_clicks were affected : https://www.dropbox.com/s/bumzx6a2mv79qo2/Screenshot%202018-02-15%2022.10.42.png?dl=0 .

I left a comment here for desktop : https://github.com/Codeinwp/themeisle-blog/issues/10, for mobile is pretty straight-forward, we should lower the font, the line-height and probably side margins ( again, let's see qz.com or medium)

**Comment by ineagu** [comment]
the relevant info is: https://www.dropbox.com/s/nq2x4t3oy6sf9dt/Screenshot%202018-02-15%2022.24.04.png?dl=0

**Comment by abaicus** [comment]
Lower font size in tables a little bit.

**Comment by abaicus** [comment]
Should be ok now. 👍

**Comment by ineagu** [comment]
Meta area fail on single, we can hide 2nd part

**Comment by ineagu** [comment]
![fffdfbc6-2caf-42ca-89ae-7c688b3eae81](https://user-images.githubusercontent.com/1849868/36375837-cd7b6fc6-1568-11e8-9a47-f532b59014cd.png)

**Comment by abaicus** [comment]
👍
