### ISSUE TITLE
Blog re-design

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/themeisle-blog#13]
@cosmin-serbanescu few technical notes here 👍 

1. We'll use gutenberg instead of elementor, if we need any blocks maybe Andrei can create some. Gutenberg support global blocks as well so we can re-use some CTA sections for e.g
2. We'll use this AMP plugin : https://wordpress.org/plugins/amp/, we'll need at least the 1.0 version which is no alpha : https://github.com/Automattic/amp-wp since it support templates for themes : https://github.com/Automattic/amp-wp/wiki/Adding-Theme-Support, this is also helpful -> https://github.com/Automattic/amp-wp/wiki/Implementing-Interactivity .
3. Not sure if is better to create a child theme or our own theme?
4. We need to be careful to keep same schema markup as current site for both amp/non-amp
5. Get rid of not helpful plugins, hide disqus like we did on cwp

I guess you can work on a local environment on the theme part for now.

**Comment by ineagu** [comment]
cc @sab2ina

**Comment by ineagu** [comment]
One more thing, I am not sure if maybe it makes sense to use the same theme for themeisle blog/themeisle-site, even if those are different sites, I am thinking that some elements like header/footer would stay the same + some basic settings/typography. So we can have 1 parent theme for both sites and then a child for each.

just a thought maybe @rodica-andronache can have some ideas on this technical part.

**Comment by cosmin-serbanescu** [comment]
@ineagu , as discussed with @sab2ina I'm attaching here a rough estimate on the Themeisle Blog part: 
[ThemeIsle Blog Estimate.xlsx](https://github.com/Codeinwp/themeisle-blog/files/2223454/ThemeIsle.Blog.Estimate.xlsx)
- I will be needing the mockups and once I have those I'll try to find a solution for getting the assests from Sketch or maybe Mizan can simply send us the assets (footer graphics, banners etc)
- From what I've seen he used multiple fonts and I wonder what are the final ones - Sofia Pro, Filson, Museo Sans, Work Sans, Muli. Also discovered this gem: https://designtheway.com/most-used-fonts-alternative-google-fonts/ so I don't really think we need to use premium paid fonts if those have free great alternatives.
