### ISSUE TITLE
Non-https link in the top menu

### ISSUE THREAD

**Issue by carlosinho** [Codeinwp/themeisle-blog#14]
the top menu link to "blog" links to non-https version
and there's no redirection
so the page stays at http

**Comment by cosmin-serbanescu** [comment]
fixed it, you might need to clear browser cache to see it properly

**Comment by carlosinho** [comment]
Still no redirection if someone goes to non-https version.

**Comment by cosmin-serbanescu** [comment]
The redirect for http://themeisle.com/blog/ is now set.

**Comment by carlosinho** [comment]
What about redirects for all the other http URLs? Like for blog posts? I worry this might be indexed twice by Google, unless we have a 301 in place or canonical set properly.

**Comment by ineagu** [comment]
should be a wild-card redirect here on the hosting level, all http to https

cc @selul

**Comment by carlosinho** [comment]
That doesn't seem to be there. You can go to non-https version of every blog post.

**Comment by ineagu** [comment]
you are right, however this doesn't seem to be a huge deal, would ask hosting to redirect
