### ISSUE TITLE
create featured images template

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/themeisle-blog#5]
@abaicus can we try here something like we did on RS, not sure the current ones are the best we can do.

**Comment by ineagu** [comment]
@abaicus @bogdanpopa90 

I want a contest here!

The goal is to create 1 or several templates for our featured images, the challenges are : 

- the image should look well on blog single/blog
- the image should look well on fb/twitter when posted
- the image should look well on youtube thumbnail

Alternatively we can have different templates for the networks, however ideally if we can have 1 variation to work well on all, is much better. Here is an e.g on YT : https://www.dropbox.com/s/zkgnaqyt3l193dk/Screenshot%202017-01-25%2015.20.43.png?dl=0 ( first image is the best one )

**Comment by ineagu** [comment]
cc @rodica-andronache

**Comment by abaicus** [comment]
How about something like this? :D 
@bogdanpopa90 helped 
![thumbnails1](https://cloud.githubusercontent.com/assets/15010186/22553096/2b9779ec-e964-11e6-9f1a-acdaae45991e.png)

**Comment by ineagu** [comment]
How the blog featured images would look like?

**Comment by abaicus** [comment]
I think it fits pretty well. As @bogdanpopa90 said though... it might hurt when the characters are posted multiple times though... 

![archive](https://cloud.githubusercontent.com/assets/15010186/22554350/685ee5d2-e968-11e6-93f0-064588b9b347.jpg)

**Comment by ineagu** [comment]
1. Cred ca putem folosi imagini diferite pt blog, se vede putin cam mare asa, cum ar veni imaginea pe single post ca si featured + facebook ?

2. Putem face un exemplu doar cu text, fara caracter

3. Putem face si pt YT 2 exemple : 1. cu fata unui om in loc de caracter , 2. doar cu text + icon ceva

4. Ultima problema sunt culorile, nu m i se pare ca culoarea asta ma duce cu gandul la brandul themeisle, stiu ca nu avem o identitate precisa, dar am putea sa pastram putin ceva linii cred nu ?

**Comment by ineagu** [comment]
@abaicus @bogdanpopa90 Aici pentru youtube am rezolvat, asa ca ar ramane doar partea de featured image pt blog/social media, ceva in genul revive.social ar fi super :D

**Comment by abaicus** [comment]
Super, o sa o fac maine pentru blog atunci :D

**Comment by ineagu** [comment]
ping
