### ISSUE TITLE
plugin infocard not loading 

### ISSUE THREAD

**Issue by dascalescuro** [Codeinwp/themeisle-blog#6]
I know we are using a plugin to load data from the plugins we recommend but on my end I usually get this - http://prntscr.com/ersjqu or http://prnt.sc/en1o2s

It is weird because I am connected with the wi-fi and in the console it says "poor network connectivity"...

**Comment by rodica-andronache** [comment]
that is happening for me too

**Comment by ineagu** [comment]
can I see the js error ? I can't replicate the issue

**Comment by dascalescuro** [comment]
http://prntscr.com/eruica

and the log below

`jquery-migrate.min.js:2 JQMIGRATE: Migrate is installed, version 1.4.1
themeisle.com/:196 A Parser-blocking, cross-origin script, https://widgets.shopifyapps.com/assets/widgets/embed/client.js, is invoked via document.write. This may be blocked by the browser if the device has poor network connectivity. See https://www.chromestatus.com/feature/5718547946799104 for more details.
(anonymous) @ themeisle.com/:196
themeisle.com/:196 A Parser-blocking, cross-origin script, https://widgets.shopifyapps.com/assets/widgets/embed/client.js, is invoked via document.write. This may be blocked by the browser if the device has poor network connectivity. See https://www.chromestatus.com/feature/5718547946799104 for more details.
(anonymous) @ themeisle.com/:196
fontawesome-webfont.woff2 Failed to load resource: the server responded with a status of 404 ()
fontawesome-webfont.woff Failed to load resource: the server responded with a status of 404 ()
fontawesome-webfont.ttf Failed to load resource: the server responded with a status of 404 ()
jquery-1.7.2.min.js:4 Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
send @ jquery-1.7.2.min.js:4
www.gstatic.com/recaptcha/api2/r20170329125654/recaptcha__en.js:303 Uncaught Error: ReCAPTCHA placeholder element must be an element or id
    at Object.Ao [as render] (www.gstatic.com/recaptcha/api2/r20170329125654/recaptcha__en.js:303)
    at myCallBack (4:200)
    at We (www.gstatic.com/recaptcha/api2/r20170329125654/recaptcha__en.js:56)
    at www.gstatic.com/recaptcha/api2/r20170329125654/recaptcha__en.js:307
    at www.gstatic.com/recaptcha/api2/r20170329125654/recaptcha__en.js:402
https://themeisle.com/blog/wordpress-wedding-website/https://ps.w.org/gwoll…88?rev=1114688?rev=1114688?rev=1114688?rev=1114688?rev=1114688?rev=1114688 Failed to load resource: net::ERR_CONNECTION_CLOSED
`
