### ISSUE TITLE
Allow blog Contributors to add images

### ISSUE THREAD

**Issue by s2abina** [Codeinwp/themeisle-blog#7]
Can we make this change to TI blog - please check if the code is correct:

Add this code in your current theme's functions.php

if ( current_user_can('contributor') && !current_user_can('upload_files') )
    add_action('admin_init', 'allow_contributor_uploads');
function allow_contributor_uploads() {
    $contributor = get_role('contributor');
    $contributor->add_cap('upload_files');
}

It's the last answer from here:
https://wordpress.stackexchange.com/questions/77613/allow-contributor-role-to-upload-images-and-not-edit-already-published-articles

**Comment by ineagu** [comment]
@s2abina I think it makes more sense to either : 

1. Ask them to write in markup/ google docs etc for testing
2.Create an author account for them
3. Host images on dropbox

For safety reasons contributors accounts are built like this I suppose, above solutions are faster than deciding if changing that code makes sense or not and releasing an update.

**Comment by s2abina** [comment]
Okay, we will manage the Contributor's articles with images linked from Dropbox.
I'm closing the issue.
